# --- 0. Environment Setup ---
rm(list = ls())
library(fredr)
library(tidyverse)
library(lubridate)

fredr_set_key("d66e8c49c188ecf6f774d5e55bb275b9")


# --- 1. Data Fetching and Processing ---
# 1.1 Process FRED data that needs aggregation (including CPI for inflation calculation)
series_to_aggregate <- c(
  t_bill_3m = "DTB3",
  t_note_10y = "DGS10",
  brent_oil = "DCOILBRENTEU",
  dollar_index = "DTWEXBGS",
  cpi_inflation_rate = "CPIAUCSL" # Name it directly as the final desired variable name
)

fred_aggregated_quarterly <- map_dfr(
  names(series_to_aggregate),
  ~ fredr(
    series_id = series_to_aggregate[.],
    # Fetch data one year in advance for CPI year-over-year calculation
    observation_start = as.Date("2007-10-01"),
    observation_end = as.Date("2024-12-31")
  ) |> mutate(friendly_name = .) # Add friendly name as a column
) |>
  # Special handling for CPI data to calculate year-over-year inflation rate
  group_by(friendly_name) |>
  mutate(
    value = if_else(
      friendly_name == "cpi_inflation_rate",
      ((value / lag(value, 12)) - 1) * 100,
      value
    )
  ) |>
  ungroup() |>
  filter(!is.na(value)) |> # Remove NA values generated by lag()
  # Aggregate all series quarterly
  group_by(
    friendly_name,
    quarter_start_date = floor_date(date, "quarter")
  ) |>
  summarise(avg_value = mean(value), .groups = "drop") |>
  # Pivot to wide format
  pivot_wider(names_from = friendly_name, values_from = avg_value)


# 1.2 Process FRED data that is already quarterly
wb_commodities_quarterly <- fredr(
  series_id = "PALLFNFINDEXQ",
  observation_start = as.Date("2008-10-01"),
  observation_end = as.Date("2024-12-31")
) |>
  select(quarter_start_date = date, wb_commodities = value)


# 1.3 Process BDI and EPU data (from BDI.csv)
bdi_epu_quarterly <- read_csv(
  "BDI.csv",
  col_types = cols(Date = col_date(format = "%m/%d/%Y"), BDI = col_character(), EPU = col_double())
) |>
  mutate(BDI = parse_number(BDI)) |>
  group_by(quarter_start_date = floor_date(Date, "quarter")) |>
  summarise(bdi_avg = mean(BDI, na.rm = TRUE), epu_avg = mean(EPU, na.rm = TRUE), .groups = "drop")


# 1.4 Process VIX data (from VIX_History.csv)
vix_quarterly <- read_csv(
  "VIX_History.csv",
  col_types = cols(DATE = col_date(format = "%m/%d/%Y"), VIX = col_double())
) |>
  group_by(quarter_start_date = floor_date(DATE, "quarter")) |>
  summarise(vix_avg = mean(VIX, na.rm = TRUE), .groups = "drop")


# --- 2. Merge All Data Sources ---

# Put all processed data frames into a list
list_of_dfs <- list(
  fred_aggregated_quarterly,
  wb_commodities_quarterly,
  bdi_epu_quarterly,
  vix_quarterly
)

# Use purrr::reduce for a chained left_join to merge all data frames
merged_data <- reduce(list_of_dfs, left_join, by = "quarter_start_date")


# --- 3. Final Calculation and Cleanup ---

final_global_env_vars <- merged_data |>
  # Calculate term spread and real interest rate
  mutate(
    term_spread = t_note_10y - t_bill_3m,
    real_interest_rate = t_bill_3m - cpi_inflation_rate
  ) |>
  # Remove the intermediate variable cpi_inflation_rate used for calculation
  select(-cpi_inflation_rate) |>
  # Ensure all columns are in a logical order and sorted by date
  select(
    quarter_start_date, t_bill_3m, t_note_10y, term_spread, real_interest_rate,
    dollar_index, brent_oil, wb_commodities, bdi_avg, epu_avg, vix_avg
  ) |>
  arrange(quarter_start_date) |>  
  # Ensure only data from 2008-Q4 onwards is kept
  filter(quarter_start_date >= as.Date("2008-10-01"))
